Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Vegglee, pull requests merged in 2023-11, with the labels that each got.

#3 S02 us1 affichages legumes
  backend/database/schema.sql
  backend/package.json
  backend/src/router.js
  frontend/.eslintrc.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/LegumeCard.css
  frontend/src/components/LegumeCard.jsx
  frontend/src/main.jsx
Labels: Review Formateur

#5 S02 us card detail
  backend/src/router.js
  frontend/src/components/.button.css
  frontend/src/components/LegumeCard.css
  frontend/src/components/LegumeCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/OneVegetable.css
  frontend/src/pages/OneVegetable.jsx
Labels: Review Team

#9 supression de table mini_panier (non utilisée)
  backend/database/schema.sql
Labels: Review Team

#6 S03 us recette
  backend/database/schema.sql
  backend/src/router.js
  frontend/src/components/RecipeCard.css
  frontend/src/components/RecipeCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/RecipePage.css
  frontend/src/pages/RecipePage.jsx
Labels: Changed Asked

#8 Display one basket
  backend/database/schema.sql
  backend/src/router.js
  frontend/src/assets/basket.json
  frontend/src/components/Panier.jsx
  frontend/src/components/Paniers.css
  frontend/src/main.jsx
  frontend/src/pages/NosPaniersPage.jsx
  frontend/src/pages/PanierDetailsPage.css
  frontend/src/pages/PanierDetailsPage.jsx
Labels: Review Formateur

#13 Nav bar
  frontend/src/App.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/pages/NosPaniersPage.jsx
Labels: Review Formateur

#12 Formulaire de Tessa
  frontend/src/App.jsx
  frontend/src/main.jsx
  frontend/src/pages/FormulairePage.css
  frontend/src/pages/FormulairePage.jsx
  frontend/src/pages/HomePage.jsx
Labels: Review Formateur

#11 S04 recette detail
  backend/database/schema.sql
  backend/src/router.js
  frontend/src/components/LegumeCard.css
  frontend/src/components/RecipeCard.css
  frontend/src/main.jsx
  frontend/src/pages/OneRecipe.css
  frontend/src/pages/OneRecipe.jsx
  frontend/src/pages/OneVegetable.css
  frontend/src/pages/RecipePage.jsx
Labels: Review Formateur

#18 Footer advice
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Layout.jsx
  frontend/src/assets/advice1.jpg
  frontend/src/assets/advice2.jpg
  frontend/src/assets/advice3.jpg
  frontend/src/assets/advice4.jpg
  frontend/src/assets/backgroundVegetable.jpg
  frontend/src/components/Advice.jsx
  frontend/src/components/Baclground.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/LegumeCard.css
  frontend/src/components/Panier.jsx
  frontend/src/components/Paniers.css
  frontend/src/components/advice.css
  frontend/src/components/adviceData.json
  frontend/src/components/background.css
  frontend/src/components/footer.css
  frontend/src/main.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/NosPaniersPage.css
  frontend/src/pages/NosPaniersPage.jsx
  frontend/src/pages/OneVegetable.css
  frontend/src/pages/PanierDetailsPage.jsx
Labels: Review Formateur, Review Team
